name: 🆕 Mirror a public repository
description: Create a 'local' mirror within our mirror organization from an upstream.
title: "[Mirror Repo] Mirror public git repository"
labels:
  - repo-mirror
body:
  - type: dropdown
    attributes:
      label: Source Repo Provider
      description: What system does this repository live in?
      options:
        - github.com
        - gitlab.com
        - bitbucket.org
    validations:
      required: true
  - type: input
    attributes:
      label: Source Repo URL
      description: Enter the URL of the source repository
      value: https://github.com/linuxserver/docker-swag
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Target Organization
      description: What organization are we going to mirror this into?
      multiple: false
      options:
        - TeknofileNet
    validations:
      required: true
