name: GitHub actions Demo
run-name: ${{ github.actor }} is testing out GitHub actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Congrats. This job was auto triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }}."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repo
        run: |
          ls -alh ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."
  MirrorJob:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        id: hello
        uses: ./../actions/hello-world-action
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
